language: bash
dist: focal
sudo: required

env:
  - TAG=0.16.0.0-rc3

install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - git clone https://github.com/docker-library/official-images.git official-images

before_script:
  - env | sort
  - image="strophy/dashd:$TAG"
  - docker version
  - docker buildx version

script:
  - docker build -t "$image" .
  - official-images/test/run.sh "$image"
  - test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
